#!/usr/bin/env bash
#MISE description="Create files, ensuring parent directories exist"
#MISE dir="{{cwd}}"
#USAGE flag "-v --verbose" help="Print actions"
#USAGE flag "-d --dry-run" help="Dry-run mode (no filesystem changes)"
#USAGE flag "-f --force" help="Ignore mkdir/touch errors"

set -euo pipefail

VERBOSE="${usage_verbose:-false}"
DRY_RUN="${usage_dry_run:-false}"
FORCE="${usage_force:-false}"

mktouch() {
  for f in "$@"; do
    dir="$(dirname "$f")"

    $VERBOSE && printf "mkdir -p %s\n" "$dir"
    if ! $DRY_RUN; then
      mkdir -p "$dir" || { $FORCE || return 1; }
    fi

    $VERBOSE && printf "touch %s\n" "$f"
    if ! $DRY_RUN; then
      touch "$f" || { $FORCE || return 1; }
    fi
  done
}

main() {
  mktouch "$@"
}

main "$@"
